from . import payroll_adjustment
from . import payroll_month_lock
from . import payroll_payslip,payroll_salary_structure
from  . import payroll_daily
from . import hr_employee_wage_history
from . import hr_employee_wage_change_wizard
from . import hr_employee_dayoff_change_wizard
from  . import hr_employee
from . import payroll_bonus_deduction_report
from . import payroll_daily_worker_summary